# Generated by Django 3.2 on 2021-04-29 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_info_imdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='more',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
