# Generated by Django 3.2 on 2021-04-29 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_info_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='icon',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='info',
            name='poster',
            field=models.URLField(null=True),
        ),
    ]
