# Generated by Django 3.2 on 2021-04-29 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210429_2121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='country',
        ),
        migrations.RemoveField(
            model_name='info',
            name='stream',
        ),
        migrations.AddField(
            model_name='info',
            name='Stream',
            field=models.CharField(choices=[('YT', 'YouTube'), ('HT', 'Hotstar'), ('NF', 'Netflix'), ('PV', 'Prime Videos'), ('HU', 'hulu')], max_length=30, null=True),
        ),
    ]
